extends: airbnb-base
plugins:
  - import
rules:
  no-console:
    off
  import/no-dynamic-require:
    off
  no-use-before-define:
    off
  no-throw-literal:
    off
  object-curly-newline:
    off
env:
  mocha:
    true
